FROM ubuntu:16.04

RUN apt update \
  && apt upgrade -y \
  && dpkg --add-architecture i386 \
  && apt update \
  && apt install -y build-essential \
                    m4 \
                    mesa-common-dev \
                    python-dev \
                    libbz2-dev \
                    scons \
                    subversion \
                    libc6-dev-i386 \
                    g++-multilib \
                    libx11-dev:i386 \
                    libxxf86vm-dev:i386 \
                    libopenal-dev:i386 \
                    libasound2-dev:i386 \
                    libxext-dev:i386

# TODO: get from internet somewhere without dodgy redirect URL...
COPY boost_1_57_0.tar.gz /tmp/

RUN tar -xvf /tmp/boost_1_57_0.tar.gz -C /tmp \
  && cd /tmp/boost_1_57_0 \
  && ./bootstrap.sh \
  && ./bjam -j6 release link=static threading=multi \
            address-model=64 runtime-link=static \
            cxxflags='-fPIC' stage \
            /boost/chrono \
            /boost/date_time \
            /boost/filesystem \
            /boost/program_options \
            /boost/regex \
            /boost/system \
            /boost/thread
